version: '3.9'

services:
  app:
    build: ./front-end
    container_name: app_frontend
    ports: 
      - 8080:8080
    platform: linux/x86_64 
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "lsof", "-t", "-i:8080" ]
      timeout: 10s
      retries: 5
  backend:
    build: ./back-end
    container_name: app_backend
    ports:
      - 3001:3001
    platform: linux/x86_64
    restart: 'always'
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PORT=3001
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Rafa@123
      - MYSQL_HOST=db
      - MYSQL_DATABASE=cashforce_v3
    healthcheck:
      test: [ "CMD", "lsof", "-t", "-i:3001" ]
      timeout: 10s
      retries: 5
  db:
    image: mysql:8.0.21
    platform: linux/x86_64 
    container_name: db
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=Rafa@123
    restart: 'always'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 5